version: '3.8'

services:
  app:
    image: microtest
    container_name: postService
    depends_on:
      - mongodb
#      - rabbitMQ
    environment:
      ROCKET_DATABASES: '{postservice={url="mongodb://dbMongoDB:27017"}}'
#      RABBIT_HOST: QueueRabbitMQ
#      RABBIT_PORT: 5672
#      RABBIT_USER: guest
#      RABBIT_PASS: guest
    ports:
      - "8000:8000"

  mongodb:
    image: 'mongo:latest'
    container_name: dbMongoDB
    volumes:
      - dbData:/var/lib/mongodb
    ports:
      - "27017:27017"

#  rabbitMQ:
#    image: 'rabbitmq:3-management'
#    container_name: QueueRabbitMQ
#    volumes:
#      - dbData:/var/lib/rabbitmq
#    ports:
#      - "15672:15672"
#      - "5672:5672"

volumes:
  dbData:
