[default.databases.postservice]
url = "mongodb://localhost:27017"
## ROCKET_DATABASES='{postservice={url="mongodb://localhost:27017"}}'


[default]
log_level = "normal"
#adress = "0.0.0.0"
#port = "8000"
